BookStore/Models/Book.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.UserOrderedBooks = new HashSet<UserOrderedBook>();
        }
    
        public int bookId { get; set; }
        public string bookTitle { get; set; }
        public string bookDiscription { get; set; }
        public string bookImage { get; set; }
        public string bookPrice { get; set; }
        public int bookQuantity { get; set; }
        public string bookAuthorName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOrderedBook> UserOrderedBooks { get; set; }
    }
}

BookStore/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;

namespace BookStore.Controllers
{
    public class AdminsController : Controller
    {
        private BookStoreDB db = new BookStoreDB();

        // GET: Login
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Login(Admin admin)
        {
            try
            {
                var search_admin = db.Admins.Single(item => item.adminEmail == admin.adminEmail && item.adminPassword == admin.adminPassword);
                Session["username"] = "Admin";
                return RedirectToAction("../Home/index");
            }
            catch
            {
                ModelState.AddModelError("", "Username or Password is Wrong.");
            }

            return View(admin);
        }


        // GET: Admins/Create
        public ActionResult CreateBook()
        {
            return RedirectToAction("../Books/CreateBook");
        }

        // GET: Admins/Edit/5
        public ActionResult EditBook(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return RedirectToAction("../Books/EditBook/" + id);
        }

        // GET: Admins/Delete/5
        public ActionResult DeleteBook(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return RedirectToAction("../Books/DeleteBook/" + id);
        }
    }
}

BookStore/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;

namespace BookStore.Controllers
{
    public class BooksController : Controller
    {
        private BookStoreDB db = new BookStoreDB();

        // GET: Books
        public ActionResult Index()
        {
            return View(db.Books.ToList());
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        public ActionResult CreateBook()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateBook(Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("../Home/index");
            }
            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult EditBook(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditBook(Book book, string bookImage)
        {
            if (ModelState.IsValid)
            {
                book.bookImage = CheckPhoto(book, bookImage);
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        public ActionResult DeleteBook(int id)
        {
            return View(GetBook(id));
        }


        // POST: Books/Delete/5
        [HttpPost, ActionName("DeleteBook")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteBookConfirm(int id)
        {
            db.Books.Remove(GetBook(id));
            db.SaveChanges();
            return RedirectToAction("../Home/Index");
        }

        //to get the spicsific book 
        private Book GetBook(int? id)
        {
            return (db.Books.Find(id));
        }

        //GET: Users/CheckPhoto
        public string CheckPhoto(Book Book, string bookImage)
        {
            if (bookImage != null)
            {
                return bookImage;
            }
            else
            {
                return Book.bookImage;
            }
        }
    }
}

BookStore/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class UsersController : Controller
    {
        private BookStoreDB bookStoreDataBase = new BookStoreDB();

        // GET: Users/UserSignUp
        public ActionResult SignUp()
        {
            return View();
        }

        // POST: Users/USerSignUp
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(User user)
        {
            if (ModelState.IsValid)
            {
                Session["ID"] = user.userID;
                Session["username"] = user.userFirstName.ToString();
                bookStoreDataBase.Users.Add(user);
                bookStoreDataBase.SaveChanges();
                return RedirectToAction("../Home/Index");
            }

            return View(user);
        }

        // GET: Users/EditUserInfo
        public ActionResult EditUserInfo(int id)
        {
            return View(FindUser(id));
        }

        // POST: Users/EditUserInfo
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUserInfo(User user, string userImage)
        {
            if (ModelState.IsValid)
            {
                user.userImage = CheckPhoto(user, userImage);
                bookStoreDataBase.Entry(user).State = EntityState.Modified;
                bookStoreDataBase.SaveChanges();
                return RedirectToAction("../Home/Index");
            }
            return View(user);
        }

        //Get: Users/FindUser
        public User FindUser(int id)
        {
            User user = bookStoreDataBase.Users.Find(id);
            return user;
        }
    }
}

BookStore/Views/Books/CreateBook.cshtml
@model BookStore.Models.Book

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Add Book</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" sizes="15x15" href="~/Images/logo.png">
    <link href="~/Css/bootstrap-5.0.2-dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Css/font-awesome-4.7.0/css/font-awesome.min.css">
    <link href="~/Css/index.css" rel="stylesheet" />
    <style>
        .navbar .navbar-nav {
            margin-right: 45%;
        }

        .navbar .navbar-brand {
            margin-right: 35%
        }

        .loginForm {
            margin: 55px 500px;
        }
    </style>
</head>
<body>
    <!--start navbar-->
    <nav class="navbar navbar-expand-sm">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">E-bookstore</a>
            <!--button in case mobile-->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="mynavbar">
                <ul class="navbar-nav">
                    <li class="nav-item row" style="flex-direction:row; align-items:center; flex-wrap:nowrap">
                        <i class="fa fa-shopping-cart col-1" aria-hidden="true"></i>
                        @Html.ActionLink("Your Cart", "../UserOrderedBooks/Index", new { id = Convert.ToInt32(Session["ID"]) }, new { @class = "nav-link col-10" })
                    </li>
                </ul>
                <!--show when user login-->
                @if (Session["username"] != null)
                {
                    <div class="d-flex" id="user_login">
                        @if (Session["username"].ToString() == "Admin")
                        {
                            <a id="user_name" class="nav-link" style="text-decoration:underline;" href="@Url.Action("CreateBook", "Books")">Add Book</a>
                        }
                        else
                        {
                            <a id="user_name" class="nav-link" style="text-decoration:underline;" href="@Url.Action("EditUserInfo/" + Convert.ToInt32(Session["ID"]) , "Users")">@Session["UserName"].ToString()</a>
                        }
                        @Html.ActionLink("Logout", "../Home/Logout", null, new { @class = "nav-link" })
                    </div>
                }
                else
                {
                    <div class="d-flex" style="align-items: center;" id="guest">
                        @Html.ActionLink("Sign up", "../Users/SignUp", null, new { @class = "nav-link" })
                        /
                        @Html.ActionLink("Login", "../Users/Login", null, new { @class = "nav-link" })
                    </div>
                }
            </div>
        </div>
    </nav>
    <!--end navbar-->
    <div class="container">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="row">
                <div class="form-horizontal">
                    <br />
                    <h3 style="margin-bottom:10px">New Book</h3>
                    <div class="form-group">
                        <label for="name" class="form-label">Book name:</label>
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.bookTitle, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.bookTitle, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="info" class="form-label">Book info:</label>
                        <div class="col-md-4">
                            @Html.TextAreaFor(model => model.bookDiscription, new { @class = "form-control", rows = "3" })
                            @Html.ValidationMessageFor(model => model.bookDiscription, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="category" class="form-label">Price:</label>
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.bookPrice, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.bookPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4">
                            <label for="photo" class="form-label">Book image</label>
                            @Html.TextBoxFor(model => model.bookImage, new { @class = "form-control", type = "file" })
                            @Html.ValidationMessageFor(model => model.bookImage, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4">
                            <label for="director" class="form-label">Book Author Name:</label>
                            @Html.EditorFor(model => model.bookAuthorName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.bookAuthorName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4">
                            <label for="director" class="form-label">Book Quantity:</label>
                            @Html.EditorFor(model => model.bookQuantity, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.bookAuthorName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-dark" style="width:100px;margin:15px 0px" />
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>

    <!--start footer-->
    <footer>
        <div class="container">
            <h3>Copyrights © 2022 All rights reserved</h3>
        </div>
    </footer>
    <!--end footer-->

</body>
</html>

BookStore/Views/Books/DeleteBook.cshtml
@model BookStore.Models.Book

@{
    Layout = null;
}

@if (Convert.ToString(Session["username"]) != "Admin")
{
    @Html.Action("Login", "Admins")

}
else
{

    <!DOCTYPE html>

    <html>
    <head>
        <title>Delet Movie</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" sizes="15x15" href="~/Images/logo.png">
        <link href="~/Css/bootstrap-5.0.2-dist/css/bootstrap.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/Css/font-awesome-4.7.0/css/font-awesome.min.css">
        <link href="~/Css/index.css" rel="stylesheet" />
        <style>
            .navbar .navbar-nav {
                margin-right: 45%;
            }

            .navbar .navbar-brand {
                margin-right: 35%
            }

            .loginForm {
                margin: 55px 500px;
            }
        </style>
    </head>
    <body>
        <!--start navbar-->
        <nav class="navbar navbar-expand-sm">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">E-bookstore</a>
                <!--button in case mobile-->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="mynavbar">
                    <ul class="navbar-nav">
                        <li class="nav-item row" style="flex-direction:row; align-items:center; flex-wrap:nowrap">
                            <i class="fa fa-shopping-cart col-1" aria-hidden="true"></i>
                            @Html.ActionLink("Your Cart", "../UserOrderedBooks/Index", new { id = Convert.ToInt32(Session["ID"]) }, new { @class = "nav-link col-10" })
                        </li>
                    </ul>
                    <!--show when user login-->
                    @if (Session["username"] != null)
                    {
                        <div class="d-flex" id="user_login">
                            @if (Session["username"].ToString() == "Admin")
                            {
                                <a id="user_name" class="nav-link" style="text-decoration:underline;" href="@Url.Action("CreateBook", "Books")">Add Book</a>
                            }
                            else
                            {
                                <a id="user_name" class="nav-link" style="text-decoration:underline;" href="@Url.Action("EditUserInfo/" + Convert.ToInt32(Session["ID"]) , "Users")">@Session["UserName"].ToString()</a>
                            }
                            @Html.ActionLink("Logout", "../Home/Logout", null, new { @class = "nav-link" })
                        </div>
                    }
                    else
                    {
                        <div class="d-flex" style="align-items: center;" id="guest">
                            @Html.ActionLink("Sign up", "../Users/SignUp", null, new { @class = "nav-link" })
                            /
                            @Html.ActionLink("Login", "../Users/Login", null, new { @class = "nav-link" })
                        </div>
                    }
                </div>
            </div>
        </nav>
        <!--end navbar-->
        <!-- start confirm -->
        <div class="container">
            <br />
            <div class="row">
                <h3 style="margin-bottom:5px">Do you want to delete: @Model.bookTitle ?</h3>
                <img src="~/Images/BooksCovers/@Model.bookImage" alt="@Model.bookTitle" style="height:20%; width:30%; margin-top:1%" />

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-actions no-color ">
                        <input type="submit" value="Delete" class="btn btn-danger" style="width:100px; margin:10px;" />
                    </div>
                }
            </div>
        </div>
        <!-- end confirm -->
        <!--start footer-->
        <footer>
            <div class="container">
                <h3>Copyrights © 2022 All rights reserved</h3>
            </div>
        </footer>
        <!--end footer-->
    </body>
</html>
}

BookStore/Views/Books/Details.cshtml
@model BookStore.Models.Book

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="~/Images/logo.png" rel="icon" />
    <link href="~/Css/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Css/Index.css" rel="stylesheet" />
    <link href="~/Css/bootstrap-5.0.2-dist/css/bootstrap.min.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>@Model.bookTitle Details</title>
    <style>
        /*coordinating the content of the movie*/
        .parent-div {
            margin-left: 50px !important;
        }
        /*coordinating the info after every title*/
        p {
            margin-left: 50px !important;
        }
        /*coordinating the back button*/
        .btn {
            margin-left: 50px !important;
        }
    </style>

</head>
<body>
    <!--start navbar-->
    <nav class="navbar navbar-expand-sm">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">E-bookstore</a>
            <!--button in case mobile-->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="mynavbar">
                <ul class="navbar-nav">
                    <li class="nav-item row" style="flex-direction:row; align-items:center; flex-wrap:nowrap">
                        <i class="fa fa-shopping-cart col-1" aria-hidden="true"></i>
                        @Html.ActionLink("Your Cart", "../UserOrderedBooks/Index", new { id = Convert.ToInt32(Session["ID"]) }, new { @class = "nav-link col-10" })
                    </li>
                </ul>
                <!--show when user login-->
                @if (Session["username"] != null)
                {
                    <div class="d-flex" id="user_login">
                        @if (Session["username"].ToString() == "Admin")
                        {
                            <a id="user_name" class="nav-link" style="text-decoration:underline;" href="@Url.Action("func", "Admins")">@Session["UserName"].ToString()</a>
                        }
                        else
                        {
                            <a id="user_name" class="nav-link" style="text-decoration:underline;" href="@Url.Action("EditUserInfo/" + Convert.ToInt32(Session["ID"]) , "Users")">@Session["UserName"].ToString()</a>
                        }
                        @Html.ActionLink("Logout", "../Home/Logout", null, new { @class = "nav-link" })
                    </div>
                }
                else
                {
                    <div class="d-flex" style="align-items: center;" id="guest">
                        @Html.ActionLink("Sign up", "../Users/SignUp", null, new { @class = "nav-link" })
                        /
                        @Html.ActionLink("Login", "../Users/Login", null, new { @class = "nav-link" })
                    </div>
                }
            </div>
        </div>
    </nav>
    <!--end navbar-->
    <div>
        <h4>@Model.bookTitle</h4>
        <hr />

        <div class="parent-div">

            <h4>Book Name:</h4>
            <p>
                @Html.DisplayFor(model => model.bookTitle)
            </p>

            <h4>Book Descrption:</h4>
            <p>
                @Html.DisplayFor(model => model.bookDiscription)
            </p>

            <h4>Book photo:</h4>
            <p>
                <img class="col-md-4" src="~/Images/BooksCovers/@Model.bookImage" alt="@Model.bookTitle" style="height:30%; width:30%" />
            </p>

            <h4>Book Price:</h4>
            <p>
                @Html.DisplayFor(model => model.bookPrice)
            </p>

            <h4>The Book Available Quantity:</h4>
            <p>
                @Html.DisplayFor(model => model.bookQuantity)
            </p>

        </div>

    </div>

    <p>
        @if (Session["ID"] != null)
        {
            @Html.ActionLink("Add to card", "../UserOrderedBooks/AddToCart/" + Model.bookId, null, new { @Class = "btn btn-dark" })

        }
        else
        {
            @Html.ActionLink("Add to card", "../Users/Login", null, new { @Class = "btn btn-dark" })
        }
        @Html.ActionLink("Back to List", "Index", null, new { @Class = "btn btn-dark" })
    </p>

    <!--start footer-->
    <footer>
        <div class="container">
            <h3>Copyrights © 2022 All rights reserved</h3>
        </div>
    </footer>
    <!--end footer-->
</body>
</html>

BookStore/Views/Books/Index.cshtml
@model IEnumerable<BookStore.Models.Book>

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>E-book store</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" sizes="15x15" href="~/Images/logo.png">
    <link href="~/Css/bootstrap-5.0.2-dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Css/font-awesome-4.7.0/css/font-awesome.min.css">
    <link href="~/Css/index.css" rel="stylesheet" />
    <style>
        .navbar .navbar-nav {
            margin-right: 45%;
        }

        .navbar .navbar-brand {
            margin-right: 35%
        }

        .books .card {
            margin: 15px !important;
            padding: 15px 30px !important;
            border-radius: 10px;
            border: 1px solid gray;
            border-radius: 5px;
        }

            .books .card:hover {
                box-shadow: 0px 8px 16px 0px #808080;
                border-color: transparent;
            }

        .books a {
            margin-top: 15px
        }
    </style>


</head>

<body>
    <!--start navbar-->
    <nav class="navbar navbar-expand-sm">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">E-bookstore</a>
            <!--button in case mobile-->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="mynavbar">
                <ul class="navbar-nav">
                    <li class="nav-item row" style="flex-direction:row; align-items:center; flex-wrap:nowrap">
                        <i class="fa fa-shopping-cart col-1" aria-hidden="true" ></i>
                        @Html.ActionLink("Your Cart", "../UserOrderedBooks/Index", new { id = Convert.ToInt32(Session["ID"]) }, new { @class = "nav-link col-10" })
                    </li>
                </ul>
                <!--show when user login-->
                @if (Session["username"] != null)
                {
                    <div class="d-flex" id="user_login">
                        @if (Session["username"].ToString() == "Admin")
                        {
                            <a id="user_name" class="nav-link" style="text-decoration:underline;" href="@Url.Action("CreateBook", "Books")">Add Book</a>
                        }
                        else
                        {
                            <a id="user_name" class="nav-link" style="text-decoration:underline;" href="@Url.Action("EditUserInfo/" + Convert.ToInt32(Session["ID"]) , "Users")">@Session["UserName"].ToString()</a>
                        }
                        @Html.ActionLink("Logout", "../Home/Logout", null, new { @class = "nav-link" })
                    </div>
                }
                else
                {
                    <div class="d-flex" style="align-items: center;" id="guest">
                        @Html.ActionLink("Sign up", "../Users/SignUp", null, new { @class = "nav-link" })
                        /
                        @Html.ActionLink("Login", "../Users/Login", null, new { @class = "nav-link" })
                    </div>
                }
            </div>
        </div>
    </nav>
    <!--end navbar-->
    <!--start site opening-->
    <div class="books">
        <div class="container">
            <br />
            <h3 class="h3-underline">All books</h3>
            <div class="row justify-content-around">

                @foreach (var item in Model)
                {
                    <div class="col-3 card ">
                        <h6>@Html.DisplayFor(modelItem => item.bookTitle)</h6>
                        <div>
                            <img class="col-md-4" src="~/Images/BooksCovers/@item.bookImage" alt="@item.bookTitle" style="height:100%; width:100%" />
                        </div>
                        <div>
                            @if (Session["username"] != null && Session["username"].ToString() == "Admin")
                            {
                                @Html.ActionLink("Edit Book Info", "../Admins/EditBook", new { id = item.bookId }, new { @class = "btn btn-dark w-100" })
                            }
                            else
                            {
                                @Html.ActionLink("The Book Info", "/Details", new { id = item.bookId }, new { @class = "btn btn-dark w-100" })
                                @Html.ActionLink("Add to cart", "../UserOrderedBooks/AddToCart", new { id = item.bookId }, new { @class = "btn btn-success w-100" })
                            }
                        </div>
                    </div>
                }
            </div>

        </div>
    </div>
    <!--end site opening-->
    <!--start footer-->
    <footer>
        <div class="container">
            <h3>Copyrights © 2022 All rights reserved</h3>
        </div>
    </footer>
    <!--end footer-->
</body>

</html>